# Generated by Django 6.0.1 on 2026-01-27 14:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('district', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('Kavre', 'Kavre'), ('Nuwakot', 'Nuwakot'), ('Rasuwa', 'Rasuwa'), ('Sindhuli', 'Sindhuli'), ('Ramechhap', 'Ramechhap'), ('Dolakha', 'Dolakha'), ('Makwanpur', 'Makwanpur'), ('Ilam', 'Ilam'), ('Jhapa', 'Jhapa'), ('Morang', 'Morang'), ('Sunsari', 'Sunsari'), ('Dhankuta', 'Dhankuta'), ('Terhathum', 'Terhathum'), ('Panchthar', 'Panchthar'), ('Udayapur', 'Udayapur'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Sindhupalchok', 'Sindhupalchok'), ('Gorkha', 'Gorkha'), ('Lamjung', 'Lamjung'), ('Tanahu', 'Tanahu'), ('Chitwan', 'Chitwan'), ('Nawalpur', 'Nawalpur'), ('Parsa', 'Parsa'), ('Bara', 'Bara'), ('Rautahat', 'Rautahat'), ('Gulmi', 'Gulmi'), ('Arghakhanchi', 'Arghakhanchi'), ('Palpa', 'Palpa'), ('Dang', 'Dang'), ('Banke', 'Banke'), ('Bardiya', 'Bardiya'), ('Surkhet', 'Surkhet'), ('Salyan', 'Salyan'), ('Pyuthan', 'Pyuthan'), ('Rolpa', 'Rolpa'), ('Rukum', 'Rukum'), ('Dailekh', 'Dailekh'), ('Jumla', 'Jumla'), ('Kalikot', 'Kalikot'), ('Dolpa', 'Dolpa'), ('Jajarkot', 'Jajarkot'), ('Achham', 'Achham'), ('Bajura', 'Bajura'), ('Bajhang', 'Bajhang'), ('Doti', 'Doti'), ('Kailali', 'Kailali'), ('Kanchanpur', 'Kanchanpur')], default='Kathmandu', max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('operating_hours', models.CharField(default='9 AM - 5 PM', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_name', models.CharField(help_text='Name of restaurant/business offering discount', max_length=200)),
                ('business_type', models.CharField(help_text='e.g., Restaurant, Pharmacy, Grocery Store', max_length=100)),
                ('description', models.TextField(help_text='Description of the discount offered')),
                ('discount_percentage', models.IntegerField(help_text='Discount percentage offered')),
                ('points_cost', models.IntegerField(help_text='Points required to unlock this discount')),
                ('image', models.ImageField(blank=True, null=True, upload_to='discount_rewards/')),
                ('coupon_code', models.CharField(help_text='Unique coupon code for this discount', max_length=50, unique=True)),
                ('valid_until', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=-1, help_text='Number of available coupons (-1 for unlimited)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationDrive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('blood_groups', models.JSONField(help_text="List of blood groups needed, e.g., ['O+', 'A-']")),
                ('urgency', models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('critical', 'Critical')], max_length=20)),
                ('target_units', models.IntegerField()),
                ('collected_units', models.IntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('location', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(default='Kathmandu', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('api_key_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
            },
        ),
        migrations.CreateModel(
            name='HospitalReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_id', models.CharField(max_length=50, unique=True)),
                ('hospital_name', models.CharField(max_length=200)),
                ('district', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('Kavre', 'Kavre'), ('Nuwakot', 'Nuwakot'), ('Rasuwa', 'Rasuwa'), ('Sindhuli', 'Sindhuli'), ('Ramechhap', 'Ramechhap'), ('Dolakha', 'Dolakha'), ('Makwanpur', 'Makwanpur'), ('Ilam', 'Ilam'), ('Jhapa', 'Jhapa'), ('Morang', 'Morang'), ('Sunsari', 'Sunsari'), ('Dhankuta', 'Dhankuta'), ('Terhathum', 'Terhathum'), ('Panchthar', 'Panchthar'), ('Udayapur', 'Udayapur'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Nuwakot', 'Nuwakot'), ('Sindhupalchok', 'Sindhupalchok'), ('Gorkha', 'Gorkha'), ('Lamjung', 'Lamjung'), ('Tanahu', 'Tanahu'), ('Chitwan', 'Chitwan'), ('Nawalpur', 'Nawalpur'), ('Parsa', 'Parsa'), ('Bara', 'Bara'), ('Rautahat', 'Rautahat'), ('Gulmi', 'Gulmi'), ('Arghakhanchi', 'Arghakhanchi'), ('Palpa', 'Palpa'), ('Dang', 'Dang'), ('Banke', 'Banke'), ('Bardiya', 'Bardiya'), ('Surkhet', 'Surkhet'), ('Salyan', 'Salyan'), ('Pyuthan', 'Pyuthan'), ('Rolpa', 'Rolpa'), ('Rukum', 'Rukum'), ('Dailekh', 'Dailekh'), ('Jumla', 'Jumla'), ('Kalikot', 'Kalikot'), ('Dolpa', 'Dolpa'), ('Jajarkot', 'Jajarkot'), ('Achham', 'Achham'), ('Bajura', 'Bajura'), ('Bajhang', 'Bajhang'), ('Doti', 'Doti'), ('Kailali', 'Kailali'), ('Kanchanpur', 'Kanchanpur')], default='Kathmandu', max_length=100)),
                ('blood_type_needed', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('blood_product_needed', models.CharField(choices=[('whole_blood', 'Whole Blood'), ('plasma', 'Plasma'), ('platelets', 'Platelets')], default='whole_blood', max_length=20)),
                ('units_needed', models.IntegerField(default=1)),
                ('is_critical', models.BooleanField(default=False)),
                ('contact_phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fulfilled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(help_text='e.g., Medicine, Supplement, Healthcare Item', max_length=100)),
                ('points_cost', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_rewards/')),
                ('provider', models.CharField(help_text='Pharmacy/Healthcare provider name', max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('points_cost', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='store_items/')),
                ('stock', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('blood_product_type', models.CharField(choices=[('whole_blood', 'Whole Blood'), ('plasma', 'Plasma'), ('platelets', 'Platelets')], default='whole_blood', max_length=20)),
                ('points', models.IntegerField(default=0)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('referral_code', models.CharField(default=uuid.uuid4, max_length=20, unique=True)),
                ('total_donations', models.IntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('Kavre', 'Kavre'), ('Nuwakot', 'Nuwakot'), ('Rasuwa', 'Rasuwa'), ('Sindhuli', 'Sindhuli'), ('Ramechhap', 'Ramechhap'), ('Dolakha', 'Dolakha'), ('Makwanpur', 'Makwanpur'), ('Ilam', 'Ilam'), ('Jhapa', 'Jhapa'), ('Morang', 'Morang'), ('Sunsari', 'Sunsari'), ('Dhankuta', 'Dhankuta'), ('Terhathum', 'Terhathum'), ('Panchthar', 'Panchthar'), ('Udayapur', 'Udayapur'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Sindhupalchok', 'Sindhupalchok'), ('Gorkha', 'Gorkha'), ('Lamjung', 'Lamjung'), ('Tanahu', 'Tanahu'), ('Chitwan', 'Chitwan'), ('Nawalpur', 'Nawalpur'), ('Parsa', 'Parsa'), ('Bara', 'Bara'), ('Rautahat', 'Rautahat'), ('Gulmi', 'Gulmi'), ('Arghakhanchi', 'Arghakhanchi'), ('Palpa', 'Palpa'), ('Dang', 'Dang'), ('Banke', 'Banke'), ('Bardiya', 'Bardiya'), ('Surkhet', 'Surkhet'), ('Salyan', 'Salyan'), ('Pyuthan', 'Pyuthan'), ('Rolpa', 'Rolpa'), ('Rukum', 'Rukum'), ('Dailekh', 'Dailekh'), ('Jumla', 'Jumla'), ('Kalikot', 'Kalikot'), ('Dolpa', 'Dolpa'), ('Jajarkot', 'Jajarkot'), ('Achham', 'Achham'), ('Bajura', 'Bajura'), ('Bajhang', 'Bajhang'), ('Doti', 'Doti'), ('Kailali', 'Kailali'), ('Kanchanpur', 'Kanchanpur')], default='Kathmandu', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_consent', models.BooleanField(default=False)),
                ('location_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='api.donorprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField()),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='When the discount was actually used', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('discount_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='api.discountreward')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_redemptions', to='api.donorprofile')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_date', models.DateField()),
                ('points_awarded', models.IntegerField(default=100)),
                ('confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='api.donorprofile')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.hospitalreq')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField()),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_phone', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_redemptions', to='api.donorprofile')),
                ('medicine_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='api.medicinereward')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='MoneyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField()),
                ('esewa_amount', models.DecimalField(decimal_places=2, help_text='Amount in RS (1 RS per 100 points)', max_digits=10)),
                ('esewa_id', models.CharField(help_text='Esewa transaction ID', max_length=100, unique=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_rewards', to='api.donorprofile')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='StockAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('alert_level', models.CharField(choices=[('low', 'Low'), ('critical', 'Critical'), ('emergency', 'Emergency')], max_length=20)),
                ('threshold', models.IntegerField()),
                ('current_units', models.IntegerField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='api.hospital')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='Redemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField()),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='api.donorprofile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.storeitem')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('units_change', models.IntegerField(help_text='Positive for donation received, negative for units issued')),
                ('timestamp', models.DateTimeField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('source_reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.hospital')),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('blood_product_type', models.CharField(choices=[('whole_blood', 'Whole Blood'), ('plasma', 'Plasma'), ('platelets', 'Platelets')], default='whole_blood', max_length=20)),
                ('units_available', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='api.hospital')),
            ],
            options={
                'ordering': ['hospital__name', 'blood_group'],
                'unique_together': {('hospital', 'blood_group', 'blood_product_type')},
            },
        ),
    ]
