# Generated by Django 6.0.1 on 2026-01-28 17:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bloodrequest_smsnotificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='referral_code',
            field=models.CharField(default=api.models.generate_referral_code, max_length=20, unique=True),
        ),
    ]
