# Generated by Django 6.0.1 on 2026-01-27 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hospital_transaction_bloodstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('business_name', models.CharField(help_text='Name of restaurant/business offering discount', max_length=200)),
                ('business_type', models.CharField(help_text='e.g., Restaurant, Pharmacy, Grocery Store', max_length=100)),
                ('description', models.TextField(help_text='Description of the discount offered')),
                ('discount_percentage', models.IntegerField(help_text='Discount percentage offered')),
                ('points_cost', models.IntegerField(help_text='Points required to unlock this discount')),
                ('image', models.ImageField(blank=True, null=True, upload_to='discount_rewards/')),
                ('coupon_code', models.CharField(help_text='Unique coupon code for this discount', max_length=50, unique=True)),
                ('valid_until', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('stock', models.IntegerField(default=-1, help_text='Number of available coupons (-1 for unlimited)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(help_text='e.g., Medicine, Supplement, Healthcare Item', max_length=100)),
                ('points_cost', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='medicine_rewards/')),
                ('provider', models.CharField(help_text='Pharmacy/Healthcare provider name', max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscountRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField()),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='When the discount was actually used', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_redemptions', to='api.donorprofile')),
                ('discount_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='api.discountreward')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicineRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField()),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_phone', models.CharField(blank=True, max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_redemptions', to='api.donorprofile')),
                ('medicine_reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='api.medicinereward')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
        migrations.CreateModel(
            name='MoneyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_used', models.IntegerField()),
                ('esewa_amount', models.DecimalField(decimal_places=2, help_text='Amount in RS (1 RS per 100 points)', max_digits=10)),
                ('esewa_id', models.CharField(help_text='Esewa transaction ID', max_length=100, unique=True)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_rewards', to='api.donorprofile')),
            ],
            options={
                'ordering': ['-redeemed_at'],
            },
        ),
    ]
