# Generated by Django 6.0.1 on 2026-01-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hospital_transaction_bloodstock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodbank',
            name='city',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='hospitalreq',
            name='city',
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='district',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('Kavre', 'Kavre'), ('Nuwakot', 'Nuwakot'), ('Rasuwa', 'Rasuwa'), ('Sindhuli', 'Sindhuli'), ('Ramechhap', 'Ramechhap'), ('Dolakha', 'Dolakha'), ('Makwanpur', 'Makwanpur'), ('Ilam', 'Ilam'), ('Jhapa', 'Jhapa'), ('Morang', 'Morang'), ('Sunsari', 'Sunsari'), ('Dhankuta', 'Dhankuta'), ('Terhathum', 'Terhathum'), ('Panchthar', 'Panchthar'), ('Udayapur', 'Udayapur'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Sindhupalchok', 'Sindhupalchok'), ('Gorkha', 'Gorkha'), ('Lamjung', 'Lamjung'), ('Tanahu', 'Tanahu'), ('Chitwan', 'Chitwan'), ('Nawalpur', 'Nawalpur'), ('Parsa', 'Parsa'), ('Bara', 'Bara'), ('Rautahat', 'Rautahat'), ('Gulmi', 'Gulmi'), ('Arghakhanchi', 'Arghakhanchi'), ('Palpa', 'Palpa'), ('Dang', 'Dang'), ('Banke', 'Banke'), ('Bardiya', 'Bardiya'), ('Surkhet', 'Surkhet'), ('Salyan', 'Salyan'), ('Pyuthan', 'Pyuthan'), ('Rolpa', 'Rolpa'), ('Rukum', 'Rukum'), ('Dailekh', 'Dailekh'), ('Jumla', 'Jumla'), ('Kalikot', 'Kalikot'), ('Dolpa', 'Dolpa'), ('Jajarkot', 'Jajarkot'), ('Achham', 'Achham'), ('Bajura', 'Bajura'), ('Bajhang', 'Bajhang'), ('Doti', 'Doti'), ('Kailali', 'Kailali'), ('Kanchanpur', 'Kanchanpur')], default='Kathmandu', max_length=100),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='district',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('Kavre', 'Kavre'), ('Nuwakot', 'Nuwakot'), ('Rasuwa', 'Rasuwa'), ('Sindhuli', 'Sindhuli'), ('Ramechhap', 'Ramechhap'), ('Dolakha', 'Dolakha'), ('Makwanpur', 'Makwanpur'), ('Ilam', 'Ilam'), ('Jhapa', 'Jhapa'), ('Morang', 'Morang'), ('Sunsari', 'Sunsari'), ('Dhankuta', 'Dhankuta'), ('Terhathum', 'Terhathum'), ('Panchthar', 'Panchthar'), ('Udayapur', 'Udayapur'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Sindhupalchok', 'Sindhupalchok'), ('Gorkha', 'Gorkha'), ('Lamjung', 'Lamjung'), ('Tanahu', 'Tanahu'), ('Chitwan', 'Chitwan'), ('Nawalpur', 'Nawalpur'), ('Parsa', 'Parsa'), ('Bara', 'Bara'), ('Rautahat', 'Rautahat'), ('Gulmi', 'Gulmi'), ('Arghakhanchi', 'Arghakhanchi'), ('Palpa', 'Palpa'), ('Dang', 'Dang'), ('Banke', 'Banke'), ('Bardiya', 'Bardiya'), ('Surkhet', 'Surkhet'), ('Salyan', 'Salyan'), ('Pyuthan', 'Pyuthan'), ('Rolpa', 'Rolpa'), ('Rukum', 'Rukum'), ('Dailekh', 'Dailekh'), ('Jumla', 'Jumla'), ('Kalikot', 'Kalikot'), ('Dolpa', 'Dolpa'), ('Jajarkot', 'Jajarkot'), ('Achham', 'Achham'), ('Bajura', 'Bajura'), ('Bajhang', 'Bajhang'), ('Doti', 'Doti'), ('Kailali', 'Kailali'), ('Kanchanpur', 'Kanchanpur')], default='Kathmandu', max_length=100),
        ),
        migrations.AddField(
            model_name='hospitalreq',
            name='district',
            field=models.CharField(choices=[('Kathmandu', 'Kathmandu'), ('Bhaktapur', 'Bhaktapur'), ('Lalitpur', 'Lalitpur'), ('Kavre', 'Kavre'), ('Nuwakot', 'Nuwakot'), ('Rasuwa', 'Rasuwa'), ('Sindhuli', 'Sindhuli'), ('Ramechhap', 'Ramechhap'), ('Dolakha', 'Dolakha'), ('Makwanpur', 'Makwanpur'), ('Ilam', 'Ilam'), ('Jhapa', 'Jhapa'), ('Morang', 'Morang'), ('Sunsari', 'Sunsari'), ('Dhankuta', 'Dhankuta'), ('Terhathum', 'Terhathum'), ('Panchthar', 'Panchthar'), ('Udayapur', 'Udayapur'), ('Sankhuwasabha', 'Sankhuwasabha'), ('Nuwakot', 'Nuwakot'), ('Sindhupalchok', 'Sindhupalchok'), ('Gorkha', 'Gorkha'), ('Lamjung', 'Lamjung'), ('Tanahu', 'Tanahu'), ('Chitwan', 'Chitwan'), ('Nawalpur', 'Nawalpur'), ('Parsa', 'Parsa'), ('Bara', 'Bara'), ('Rautahat', 'Rautahat'), ('Gulmi', 'Gulmi'), ('Arghakhanchi', 'Arghakhanchi'), ('Palpa', 'Palpa'), ('Dang', 'Dang'), ('Banke', 'Banke'), ('Bardiya', 'Bardiya'), ('Surkhet', 'Surkhet'), ('Salyan', 'Salyan'), ('Pyuthan', 'Pyuthan'), ('Rolpa', 'Rolpa'), ('Rukum', 'Rukum'), ('Dailekh', 'Dailekh'), ('Jumla', 'Jumla'), ('Kalikot', 'Kalikot'), ('Dolpa', 'Dolpa'), ('Jajarkot', 'Jajarkot'), ('Achham', 'Achham'), ('Bajura', 'Bajura'), ('Bajhang', 'Bajhang'), ('Doti', 'Doti'), ('Kailali', 'Kailali'), ('Kanchanpur', 'Kanchanpur')], default='Kathmandu', max_length=100),
        ),
    ]
