# Generated by Django 6.0.1 on 2026-01-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_bloodbank_city_remove_donorprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='blood_product_type',
            field=models.CharField(choices=[('whole_blood', 'Whole Blood'), ('plasma', 'Plasma'), ('platelets', 'Platelets')], default='whole_blood', max_length=20),
        ),
        migrations.AddField(
            model_name='hospitalreq',
            name='blood_product_needed',
            field=models.CharField(choices=[('whole_blood', 'Whole Blood'), ('plasma', 'Plasma'), ('platelets', 'Platelets')], default='whole_blood', max_length=20),
        ),
    ]
