# Generated by Django 6.0.1 on 2026-01-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_donorprofile_blood_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='location_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='location_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
