# Generated by Django 6.0.1 on 2026-01-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_discountreward_medicinereward_discountredemption_and_more'),
        ('api', '0003_donationdrive_stockalert'),
        ('api', '0005_donorprofile_location_fields'),
    ]

    operations = [
    ]
