# Generated by Django 6.0.1 on 2026-01-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20260127_1833'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bloodstock',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='bloodstock',
            name='blood_product_type',
            field=models.CharField(choices=[('whole_blood', 'Whole Blood'), ('plasma', 'Plasma'), ('platelets', 'Platelets')], default='whole_blood', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='bloodstock',
            unique_together={('hospital', 'blood_group', 'blood_product_type')},
        ),
    ]
