# Generated by Django 6.0.1 on 2026-01-28 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0003_alter_donorprofile_referral_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='in_transit', max_length=20)),
                ('initial_temperature', models.DecimalField(blank=True, decimal_places=2, help_text='Initial temperature in Celsius', max_digits=5, null=True)),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bloodrequest')),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_packets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('traffic_jam_detected', models.BooleanField(default=False)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaRTimer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('ambient_temperature', models.DecimalField(decimal_places=2, help_text='Ambient temperature at pickup in Celsius', max_digits=5)),
                ('predicted_decay_time', models.PositiveIntegerField(help_text='Predicted time in minutes for temperature to become critical')),
                ('critical_threshold_time', models.PositiveIntegerField(help_text='Time in minutes when critical temperature is expected to be reached')),
                ('blood_packet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tar_timer', to='timer.bloodpacket')),
            ],
        ),
    ]
